apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-pv
  labels:
    type: local
    app: mysql
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce          # MySQL writes from a single pod only
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""       # <-- important: disables dynamic provisioning
  hostPath:
    path: /mnt/mysql-data    # <-- directory you will create on the node
    type: DirectoryOrCreate
